/**
 * Localidades de Argentina con su Código Postal central.
 * Cobertura prioritaria: CABA + AMBA (~80% de pólizas de un broker) +
 * capitales de provincia + ciudades grandes.
 *
 * Para CABA, el CP es por barrio. Para localidades chicas, el CP es único.
 * Para ciudades grandes con múltiples CPs, devolvemos el CP central
 * (el usuario puede ajustarlo manualmente si tiene el detalle por calle).
 *
 * Fuente base: Correo Argentino + dataset público AMBA.
 */

export interface LocalidadAR {
  /** Nombre canónico de la localidad (Title Case) */
  nombre: string
  /** Código Postal de 4 dígitos */
  cp: string
  /** Provincia o "CABA" */
  provincia: string
}

// ----- Helper de normalización para búsqueda (sin tildes ni mayúsculas) -----
function norm(s: string): string {
  return s
    .normalize("NFD")
    .replace(/[̀-ͯ]/g, "")
    .toLowerCase()
    .trim()
}

// ----- Dataset -----
// Ordenado por provincia para facilitar mantenimiento.
export const LOCALIDADES_AR: LocalidadAR[] = [
  // ===== CABA (por barrio) =====
  { nombre: "Microcentro", cp: "1000", provincia: "CABA" },
  { nombre: "Retiro", cp: "1001", provincia: "CABA" },
  { nombre: "San Nicolás", cp: "1032", provincia: "CABA" },
  { nombre: "Monserrat", cp: "1078", provincia: "CABA" },
  { nombre: "San Telmo", cp: "1101", provincia: "CABA" },
  { nombre: "La Boca", cp: "1158", provincia: "CABA" },
  { nombre: "Barracas", cp: "1275", provincia: "CABA" },
  { nombre: "Constitución", cp: "1150", provincia: "CABA" },
  { nombre: "Recoleta", cp: "1110", provincia: "CABA" },
  { nombre: "Balvanera", cp: "1184", provincia: "CABA" },
  { nombre: "Almagro", cp: "1186", provincia: "CABA" },
  { nombre: "Boedo", cp: "1240", provincia: "CABA" },
  { nombre: "San Cristóbal", cp: "1230", provincia: "CABA" },
  { nombre: "Parque Patricios", cp: "1260", provincia: "CABA" },
  { nombre: "Nueva Pompeya", cp: "1437", provincia: "CABA" },
  { nombre: "Villa Soldati", cp: "1439", provincia: "CABA" },
  { nombre: "Villa Lugano", cp: "1439", provincia: "CABA" },
  { nombre: "Mataderos", cp: "1440", provincia: "CABA" },
  { nombre: "Liniers", cp: "1408", provincia: "CABA" },
  { nombre: "Villa Luro", cp: "1407", provincia: "CABA" },
  { nombre: "Vélez Sarsfield", cp: "1407", provincia: "CABA" },
  { nombre: "Floresta", cp: "1407", provincia: "CABA" },
  { nombre: "Monte Castro", cp: "1407", provincia: "CABA" },
  { nombre: "Villa Real", cp: "1407", provincia: "CABA" },
  { nombre: "Villa Devoto", cp: "1419", provincia: "CABA" },
  { nombre: "Villa del Parque", cp: "1417", provincia: "CABA" },
  { nombre: "Villa Santa Rita", cp: "1416", provincia: "CABA" },
  { nombre: "Villa General Mitre", cp: "1416", provincia: "CABA" },
  { nombre: "Paternal", cp: "1416", provincia: "CABA" },
  { nombre: "Agronomía", cp: "1419", provincia: "CABA" },
  { nombre: "Parque Chas", cp: "1431", provincia: "CABA" },
  { nombre: "Villa Urquiza", cp: "1431", provincia: "CABA" },
  { nombre: "Villa Pueyrredón", cp: "1431", provincia: "CABA" },
  { nombre: "Coghlan", cp: "1430", provincia: "CABA" },
  { nombre: "Saavedra", cp: "1429", provincia: "CABA" },
  { nombre: "Núñez", cp: "1429", provincia: "CABA" },
  { nombre: "Belgrano", cp: "1428", provincia: "CABA" },
  { nombre: "Colegiales", cp: "1426", provincia: "CABA" },
  { nombre: "Palermo", cp: "1414", provincia: "CABA" },
  { nombre: "Villa Crespo", cp: "1414", provincia: "CABA" },
  { nombre: "Chacarita", cp: "1414", provincia: "CABA" },
  { nombre: "Caballito", cp: "1405", provincia: "CABA" },
  { nombre: "Flores", cp: "1406", provincia: "CABA" },
  { nombre: "Parque Chacabuco", cp: "1424", provincia: "CABA" },
  { nombre: "Parque Avellaneda", cp: "1407", provincia: "CABA" },
  { nombre: "Puerto Madero", cp: "1107", provincia: "CABA" },
  { nombre: "Capital Federal", cp: "1000", provincia: "CABA" },
  { nombre: "CABA", cp: "1000", provincia: "CABA" },
  { nombre: "Ciudad Autónoma de Buenos Aires", cp: "1000", provincia: "CABA" },

  // ===== GBA Sur (zona Avellaneda → Berazategui → Varela) =====
  { nombre: "Avellaneda", cp: "1870", provincia: "Buenos Aires" },
  { nombre: "Dock Sud", cp: "1871", provincia: "Buenos Aires" },
  { nombre: "Sarandí", cp: "1872", provincia: "Buenos Aires" },
  { nombre: "Villa Domínico", cp: "1874", provincia: "Buenos Aires" },
  { nombre: "Wilde", cp: "1875", provincia: "Buenos Aires" },
  { nombre: "Bernal", cp: "1876", provincia: "Buenos Aires" },
  { nombre: "Don Bosco", cp: "1876", provincia: "Buenos Aires" },
  { nombre: "Quilmes", cp: "1878", provincia: "Buenos Aires" },
  { nombre: "Quilmes Oeste", cp: "1879", provincia: "Buenos Aires" },
  { nombre: "Ezpeleta", cp: "1882", provincia: "Buenos Aires" },
  { nombre: "Berazategui", cp: "1880", provincia: "Buenos Aires" },
  { nombre: "Plátanos", cp: "1885", provincia: "Buenos Aires" },
  { nombre: "Ranelagh", cp: "1886", provincia: "Buenos Aires" },
  { nombre: "Hudson", cp: "1885", provincia: "Buenos Aires" },
  { nombre: "Pereyra", cp: "1893", provincia: "Buenos Aires" },
  { nombre: "Florencio Varela", cp: "1888", provincia: "Buenos Aires" },
  { nombre: "Bosques", cp: "1888", provincia: "Buenos Aires" },
  { nombre: "Villa Vatteone", cp: "1888", provincia: "Buenos Aires" },
  { nombre: "Lanús", cp: "1824", provincia: "Buenos Aires" },
  { nombre: "Lanús Oeste", cp: "1825", provincia: "Buenos Aires" },
  { nombre: "Lanús Este", cp: "1824", provincia: "Buenos Aires" },
  { nombre: "Remedios de Escalada", cp: "1826", provincia: "Buenos Aires" },
  { nombre: "Gerli", cp: "1822", provincia: "Buenos Aires" },
  { nombre: "Valentín Alsina", cp: "1822", provincia: "Buenos Aires" },
  { nombre: "Monte Chingolo", cp: "1824", provincia: "Buenos Aires" },
  { nombre: "Lomas de Zamora", cp: "1832", provincia: "Buenos Aires" },
  { nombre: "Banfield", cp: "1828", provincia: "Buenos Aires" },
  { nombre: "Temperley", cp: "1834", provincia: "Buenos Aires" },
  { nombre: "Turdera", cp: "1834", provincia: "Buenos Aires" },
  { nombre: "Llavallol", cp: "1836", provincia: "Buenos Aires" },
  { nombre: "Villa Centenario", cp: "1832", provincia: "Buenos Aires" },
  { nombre: "Ingeniero Budge", cp: "1832", provincia: "Buenos Aires" },
  { nombre: "Villa Albertina", cp: "1832", provincia: "Buenos Aires" },
  { nombre: "Almirante Brown", cp: "1846", provincia: "Buenos Aires" },
  { nombre: "Adrogué", cp: "1846", provincia: "Buenos Aires" },
  { nombre: "Burzaco", cp: "1852", provincia: "Buenos Aires" },
  { nombre: "Longchamps", cp: "1854", provincia: "Buenos Aires" },
  { nombre: "Glew", cp: "1856", provincia: "Buenos Aires" },
  { nombre: "Guernica", cp: "1862", provincia: "Buenos Aires" },
  { nombre: "Rafael Calzada", cp: "1847", provincia: "Buenos Aires" },
  { nombre: "Claypole", cp: "1849", provincia: "Buenos Aires" },
  { nombre: "Ministro Rivadavia", cp: "1850", provincia: "Buenos Aires" },
  { nombre: "José Mármol", cp: "1846", provincia: "Buenos Aires" },
  { nombre: "Don Orione", cp: "1852", provincia: "Buenos Aires" },
  { nombre: "Malvinas Argentinas", cp: "1655", provincia: "Buenos Aires" },
  { nombre: "Esteban Echeverría", cp: "1842", provincia: "Buenos Aires" },
  { nombre: "Monte Grande", cp: "1842", provincia: "Buenos Aires" },
  { nombre: "Luis Guillón", cp: "1838", provincia: "Buenos Aires" },
  { nombre: "Canning", cp: "1804", provincia: "Buenos Aires" },
  { nombre: "9 de Abril", cp: "1839", provincia: "Buenos Aires" },
  { nombre: "El Jagüel", cp: "1842", provincia: "Buenos Aires" },
  { nombre: "Ezeiza", cp: "1804", provincia: "Buenos Aires" },
  { nombre: "Tristán Suárez", cp: "1808", provincia: "Buenos Aires" },
  { nombre: "Carlos Spegazzini", cp: "1812", provincia: "Buenos Aires" },

  // ===== GBA Norte (Vicente López → Pilar → Escobar) =====
  { nombre: "Vicente López", cp: "1638", provincia: "Buenos Aires" },
  { nombre: "Olivos", cp: "1636", provincia: "Buenos Aires" },
  { nombre: "Florida", cp: "1602", provincia: "Buenos Aires" },
  { nombre: "Florida Oeste", cp: "1603", provincia: "Buenos Aires" },
  { nombre: "Munro", cp: "1605", provincia: "Buenos Aires" },
  { nombre: "Carapachay", cp: "1605", provincia: "Buenos Aires" },
  { nombre: "Villa Adelina", cp: "1607", provincia: "Buenos Aires" },
  { nombre: "La Lucila", cp: "1637", provincia: "Buenos Aires" },
  { nombre: "San Isidro", cp: "1642", provincia: "Buenos Aires" },
  { nombre: "Acassuso", cp: "1641", provincia: "Buenos Aires" },
  { nombre: "Martínez", cp: "1640", provincia: "Buenos Aires" },
  { nombre: "Beccar", cp: "1643", provincia: "Buenos Aires" },
  { nombre: "Boulogne", cp: "1609", provincia: "Buenos Aires" },
  { nombre: "Boulogne Sur Mer", cp: "1609", provincia: "Buenos Aires" },
  { nombre: "Villa Adelina", cp: "1607", provincia: "Buenos Aires" },
  { nombre: "San Fernando", cp: "1646", provincia: "Buenos Aires" },
  { nombre: "Victoria", cp: "1644", provincia: "Buenos Aires" },
  { nombre: "Virreyes", cp: "1648", provincia: "Buenos Aires" },
  { nombre: "Tigre", cp: "1648", provincia: "Buenos Aires" },
  { nombre: "Don Torcuato", cp: "1611", provincia: "Buenos Aires" },
  { nombre: "Benavídez", cp: "1621", provincia: "Buenos Aires" },
  { nombre: "Talar", cp: "1618", provincia: "Buenos Aires" },
  { nombre: "El Talar", cp: "1618", provincia: "Buenos Aires" },
  { nombre: "General Pacheco", cp: "1617", provincia: "Buenos Aires" },
  { nombre: "Rincón de Milberg", cp: "1648", provincia: "Buenos Aires" },
  { nombre: "Nordelta", cp: "1670", provincia: "Buenos Aires" },
  { nombre: "Dique Luján", cp: "1623", provincia: "Buenos Aires" },
  { nombre: "Escobar", cp: "1625", provincia: "Buenos Aires" },
  { nombre: "Belén de Escobar", cp: "1625", provincia: "Buenos Aires" },
  { nombre: "Ingeniero Maschwitz", cp: "1623", provincia: "Buenos Aires" },
  { nombre: "Garín", cp: "1619", provincia: "Buenos Aires" },
  { nombre: "Loma Verde", cp: "1625", provincia: "Buenos Aires" },
  { nombre: "Matheu", cp: "1625", provincia: "Buenos Aires" },
  { nombre: "Pilar", cp: "1629", provincia: "Buenos Aires" },
  { nombre: "Del Viso", cp: "1669", provincia: "Buenos Aires" },
  { nombre: "Manuel Alberti", cp: "1633", provincia: "Buenos Aires" },
  { nombre: "Manzanares", cp: "1635", provincia: "Buenos Aires" },
  { nombre: "Villa Rosa", cp: "1631", provincia: "Buenos Aires" },
  { nombre: "Fátima", cp: "1633", provincia: "Buenos Aires" },
  { nombre: "Tortuguitas", cp: "1667", provincia: "Buenos Aires" },
  { nombre: "Los Cardales", cp: "2814", provincia: "Buenos Aires" },
  { nombre: "Capilla del Señor", cp: "2812", provincia: "Buenos Aires" },
  { nombre: "Exaltación de la Cruz", cp: "2812", provincia: "Buenos Aires" },
  { nombre: "Zárate", cp: "2800", provincia: "Buenos Aires" },
  { nombre: "Campana", cp: "2804", provincia: "Buenos Aires" },
  { nombre: "Lima", cp: "2811", provincia: "Buenos Aires" },
  { nombre: "Alberti", cp: "6634", provincia: "Buenos Aires" },

  // ===== GBA Oeste (Morón → La Matanza → Moreno) =====
  { nombre: "Morón", cp: "1708", provincia: "Buenos Aires" },
  { nombre: "Castelar", cp: "1712", provincia: "Buenos Aires" },
  { nombre: "El Palomar", cp: "1684", provincia: "Buenos Aires" },
  { nombre: "Haedo", cp: "1706", provincia: "Buenos Aires" },
  { nombre: "Villa Sarmiento", cp: "1706", provincia: "Buenos Aires" },
  { nombre: "Ituzaingó", cp: "1714", provincia: "Buenos Aires" },
  { nombre: "Hurlingham", cp: "1686", provincia: "Buenos Aires" },
  { nombre: "Villa Tesei", cp: "1688", provincia: "Buenos Aires" },
  { nombre: "William Morris", cp: "1688", provincia: "Buenos Aires" },
  { nombre: "Tres de Febrero", cp: "1676", provincia: "Buenos Aires" },
  { nombre: "Caseros", cp: "1678", provincia: "Buenos Aires" },
  { nombre: "Sáenz Peña", cp: "1674", provincia: "Buenos Aires" },
  { nombre: "Santos Lugares", cp: "1676", provincia: "Buenos Aires" },
  { nombre: "Ciudadela", cp: "1702", provincia: "Buenos Aires" },
  { nombre: "Villa Bosch", cp: "1682", provincia: "Buenos Aires" },
  { nombre: "Loma Hermosa", cp: "1657", provincia: "Buenos Aires" },
  { nombre: "Pablo Podestá", cp: "1685", provincia: "Buenos Aires" },
  { nombre: "Churruca", cp: "1682", provincia: "Buenos Aires" },
  { nombre: "Martín Coronado", cp: "1682", provincia: "Buenos Aires" },
  { nombre: "Ramos Mejía", cp: "1704", provincia: "Buenos Aires" },
  { nombre: "Villa Luzuriaga", cp: "1754", provincia: "Buenos Aires" },
  { nombre: "Isidro Casanova", cp: "1765", provincia: "Buenos Aires" },
  { nombre: "San Justo", cp: "1754", provincia: "Buenos Aires" },
  { nombre: "La Tablada", cp: "1766", provincia: "Buenos Aires" },
  { nombre: "Aldo Bonzi", cp: "1770", provincia: "Buenos Aires" },
  { nombre: "Tapiales", cp: "1771", provincia: "Buenos Aires" },
  { nombre: "Lomas del Mirador", cp: "1752", provincia: "Buenos Aires" },
  { nombre: "Ciudad Evita", cp: "1778", provincia: "Buenos Aires" },
  { nombre: "Rafael Castillo", cp: "1755", provincia: "Buenos Aires" },
  { nombre: "González Catán", cp: "1759", provincia: "Buenos Aires" },
  { nombre: "Virrey del Pino", cp: "1763", provincia: "Buenos Aires" },
  { nombre: "Gregorio de Laferrere", cp: "1757", provincia: "Buenos Aires" },
  { nombre: "20 de Junio", cp: "1779", provincia: "Buenos Aires" },
  { nombre: "Merlo", cp: "1722", provincia: "Buenos Aires" },
  { nombre: "Libertad", cp: "1716", provincia: "Buenos Aires" },
  { nombre: "Pontevedra", cp: "1718", provincia: "Buenos Aires" },
  { nombre: "Mariano Acosta", cp: "1755", provincia: "Buenos Aires" },
  { nombre: "Marcos Paz", cp: "1727", provincia: "Buenos Aires" },
  { nombre: "Moreno", cp: "1744", provincia: "Buenos Aires" },
  { nombre: "Paso del Rey", cp: "1742", provincia: "Buenos Aires" },
  { nombre: "Trujui", cp: "1746", provincia: "Buenos Aires" },
  { nombre: "Cuartel V", cp: "1746", provincia: "Buenos Aires" },
  { nombre: "Francisco Álvarez", cp: "1746", provincia: "Buenos Aires" },
  { nombre: "La Reja", cp: "1738", provincia: "Buenos Aires" },
  { nombre: "Las Heras", cp: "1748", provincia: "Buenos Aires" },
  { nombre: "Gral. Rodríguez", cp: "1748", provincia: "Buenos Aires" },
  { nombre: "General Rodríguez", cp: "1748", provincia: "Buenos Aires" },
  { nombre: "San Miguel", cp: "1663", provincia: "Buenos Aires" },
  { nombre: "Bella Vista", cp: "1661", provincia: "Buenos Aires" },
  { nombre: "Muñiz", cp: "1663", provincia: "Buenos Aires" },
  { nombre: "Campo de Mayo", cp: "1659", provincia: "Buenos Aires" },
  { nombre: "Villa de Mayo", cp: "1666", provincia: "Buenos Aires" },
  { nombre: "Los Polvorines", cp: "1613", provincia: "Buenos Aires" },
  { nombre: "Grand Bourg", cp: "1615", provincia: "Buenos Aires" },
  { nombre: "Tortuguitas", cp: "1667", provincia: "Buenos Aires" },
  { nombre: "Ing. Pablo Nogués", cp: "1613", provincia: "Buenos Aires" },
  { nombre: "Pablo Nogués", cp: "1613", provincia: "Buenos Aires" },
  { nombre: "José C. Paz", cp: "1665", provincia: "Buenos Aires" },
  { nombre: "Sol y Verde", cp: "1665", provincia: "Buenos Aires" },

  // ===== La Plata + alrededores =====
  { nombre: "La Plata", cp: "1900", provincia: "Buenos Aires" },
  { nombre: "Tolosa", cp: "1900", provincia: "Buenos Aires" },
  { nombre: "Ringuelet", cp: "1900", provincia: "Buenos Aires" },
  { nombre: "City Bell", cp: "1896", provincia: "Buenos Aires" },
  { nombre: "Villa Elisa", cp: "1894", provincia: "Buenos Aires" },
  { nombre: "Manuel B. Gonnet", cp: "1897", provincia: "Buenos Aires" },
  { nombre: "Gonnet", cp: "1897", provincia: "Buenos Aires" },
  { nombre: "Los Hornos", cp: "1900", provincia: "Buenos Aires" },
  { nombre: "Olmos", cp: "1903", provincia: "Buenos Aires" },
  { nombre: "Lisandro Olmos", cp: "1903", provincia: "Buenos Aires" },
  { nombre: "Berisso", cp: "1923", provincia: "Buenos Aires" },
  { nombre: "Ensenada", cp: "1925", provincia: "Buenos Aires" },
  { nombre: "Punta Lara", cp: "1925", provincia: "Buenos Aires" },
  { nombre: "Magdalena", cp: "1913", provincia: "Buenos Aires" },
  { nombre: "Brandsen", cp: "1980", provincia: "Buenos Aires" },
  { nombre: "Chascomús", cp: "7130", provincia: "Buenos Aires" },
  { nombre: "Cañuelas", cp: "1814", provincia: "Buenos Aires" },
  { nombre: "Lobos", cp: "7240", provincia: "Buenos Aires" },
  { nombre: "Saladillo", cp: "7260", provincia: "Buenos Aires" },

  // ===== Costa Atlántica =====
  { nombre: "Mar del Plata", cp: "7600", provincia: "Buenos Aires" },
  { nombre: "Pinamar", cp: "7167", provincia: "Buenos Aires" },
  { nombre: "Villa Gesell", cp: "7165", provincia: "Buenos Aires" },
  { nombre: "Cariló", cp: "7167", provincia: "Buenos Aires" },
  { nombre: "Valeria del Mar", cp: "7167", provincia: "Buenos Aires" },
  { nombre: "Ostende", cp: "7167", provincia: "Buenos Aires" },
  { nombre: "Mar de Ajó", cp: "7109", provincia: "Buenos Aires" },
  { nombre: "San Bernardo", cp: "7111", provincia: "Buenos Aires" },
  { nombre: "Santa Teresita", cp: "7107", provincia: "Buenos Aires" },
  { nombre: "Mar del Tuyú", cp: "7108", provincia: "Buenos Aires" },
  { nombre: "Necochea", cp: "7630", provincia: "Buenos Aires" },
  { nombre: "Miramar", cp: "7607", provincia: "Buenos Aires" },
  { nombre: "Tandil", cp: "7000", provincia: "Buenos Aires" },
  { nombre: "Olavarría", cp: "7400", provincia: "Buenos Aires" },
  { nombre: "Azul", cp: "7300", provincia: "Buenos Aires" },
  { nombre: "Balcarce", cp: "7620", provincia: "Buenos Aires" },
  { nombre: "Dolores", cp: "7100", provincia: "Buenos Aires" },

  // ===== Resto Buenos Aires =====
  { nombre: "Bahía Blanca", cp: "8000", provincia: "Buenos Aires" },
  { nombre: "Punta Alta", cp: "8109", provincia: "Buenos Aires" },
  { nombre: "Tres Arroyos", cp: "7500", provincia: "Buenos Aires" },
  { nombre: "Pergamino", cp: "2700", provincia: "Buenos Aires" },
  { nombre: "Junín", cp: "6000", provincia: "Buenos Aires" },
  { nombre: "Mercedes", cp: "6600", provincia: "Buenos Aires" },
  { nombre: "Luján", cp: "6700", provincia: "Buenos Aires" },
  { nombre: "Chivilcoy", cp: "6620", provincia: "Buenos Aires" },
  { nombre: "Suipacha", cp: "6612", provincia: "Buenos Aires" },
  { nombre: "Bragado", cp: "6640", provincia: "Buenos Aires" },
  { nombre: "9 de Julio", cp: "6500", provincia: "Buenos Aires" },
  { nombre: "Pehuajó", cp: "6450", provincia: "Buenos Aires" },
  { nombre: "Trenque Lauquen", cp: "6400", provincia: "Buenos Aires" },
  { nombre: "Carlos Casares", cp: "6530", provincia: "Buenos Aires" },
  { nombre: "Saavedra", cp: "8170", provincia: "Buenos Aires" },
  { nombre: "Pigüé", cp: "8170", provincia: "Buenos Aires" },
  { nombre: "Coronel Suárez", cp: "7540", provincia: "Buenos Aires" },
  { nombre: "Coronel Pringles", cp: "7530", provincia: "Buenos Aires" },
  { nombre: "Coronel Dorrego", cp: "8150", provincia: "Buenos Aires" },
  { nombre: "Patagones", cp: "8504", provincia: "Buenos Aires" },
  { nombre: "Carmen de Patagones", cp: "8504", provincia: "Buenos Aires" },
  { nombre: "San Pedro", cp: "2930", provincia: "Buenos Aires" },
  { nombre: "Baradero", cp: "2942", provincia: "Buenos Aires" },
  { nombre: "San Nicolás de los Arroyos", cp: "2900", provincia: "Buenos Aires" },
  { nombre: "Ramallo", cp: "2915", provincia: "Buenos Aires" },
  { nombre: "Arrecifes", cp: "2740", provincia: "Buenos Aires" },
  { nombre: "Salto", cp: "2741", provincia: "Buenos Aires" },
  { nombre: "Rojas", cp: "2705", provincia: "Buenos Aires" },
  { nombre: "Colón", cp: "2720", provincia: "Buenos Aires" },
  { nombre: "Lincoln", cp: "6070", provincia: "Buenos Aires" },
  { nombre: "Vedia", cp: "6030", provincia: "Buenos Aires" },
  { nombre: "Chacabuco", cp: "6740", provincia: "Buenos Aires" },
  { nombre: "Carlos Tejedor", cp: "6455", provincia: "Buenos Aires" },
  { nombre: "Daireaux", cp: "6464", provincia: "Buenos Aires" },
  { nombre: "Henderson", cp: "6464", provincia: "Buenos Aires" },
  { nombre: "Tres Lomas", cp: "6409", provincia: "Buenos Aires" },
  { nombre: "Pellegrini", cp: "6451", provincia: "Buenos Aires" },
  { nombre: "Laprida", cp: "7414", provincia: "Buenos Aires" },
  { nombre: "Bolívar", cp: "6550", provincia: "Buenos Aires" },
  { nombre: "Tapalqué", cp: "7303", provincia: "Buenos Aires" },
  { nombre: "Las Flores", cp: "7200", provincia: "Buenos Aires" },
  { nombre: "Rauch", cp: "7203", provincia: "Buenos Aires" },
  { nombre: "Ayacucho", cp: "7150", provincia: "Buenos Aires" },
  { nombre: "Maipú", cp: "7160", provincia: "Buenos Aires" },
  { nombre: "Gral. Madariaga", cp: "7163", provincia: "Buenos Aires" },
  { nombre: "Pinamar Norte", cp: "7167", provincia: "Buenos Aires" },
  { nombre: "Lobería", cp: "7635", provincia: "Buenos Aires" },
  { nombre: "Tres Algarrobos", cp: "6453", provincia: "Buenos Aires" },
  { nombre: "Salliqueló", cp: "6418", provincia: "Buenos Aires" },
  { nombre: "Carhué", cp: "6430", provincia: "Buenos Aires" },
  { nombre: "Guaminí", cp: "6435", provincia: "Buenos Aires" },
  { nombre: "Cnel. Vidal", cp: "7165", provincia: "Buenos Aires" },

  // ===== Córdoba =====
  { nombre: "Córdoba", cp: "5000", provincia: "Córdoba" },
  { nombre: "Villa Carlos Paz", cp: "5152", provincia: "Córdoba" },
  { nombre: "Río Cuarto", cp: "5800", provincia: "Córdoba" },
  { nombre: "Villa María", cp: "5900", provincia: "Córdoba" },
  { nombre: "San Francisco", cp: "2400", provincia: "Córdoba" },
  { nombre: "Bell Ville", cp: "2550", provincia: "Córdoba" },
  { nombre: "Jesús María", cp: "5220", provincia: "Córdoba" },
  { nombre: "Alta Gracia", cp: "5186", provincia: "Córdoba" },
  { nombre: "Cosquín", cp: "5166", provincia: "Córdoba" },
  { nombre: "La Falda", cp: "5172", provincia: "Córdoba" },
  { nombre: "Mina Clavero", cp: "5889", provincia: "Córdoba" },
  { nombre: "Villa General Belgrano", cp: "5194", provincia: "Córdoba" },
  { nombre: "La Cumbre", cp: "5178", provincia: "Córdoba" },
  { nombre: "Capilla del Monte", cp: "5184", provincia: "Córdoba" },
  { nombre: "Marcos Juárez", cp: "2580", provincia: "Córdoba" },
  { nombre: "Río Tercero", cp: "5850", provincia: "Córdoba" },
  { nombre: "Río Segundo", cp: "5960", provincia: "Córdoba" },
  { nombre: "Arroyito", cp: "2434", provincia: "Córdoba" },
  { nombre: "Deán Funes", cp: "5200", provincia: "Córdoba" },
  { nombre: "Cruz del Eje", cp: "5280", provincia: "Córdoba" },
  { nombre: "Laboulaye", cp: "6120", provincia: "Córdoba" },
  { nombre: "Las Varillas", cp: "5940", provincia: "Córdoba" },

  // ===== Santa Fe =====
  { nombre: "Santa Fe", cp: "3000", provincia: "Santa Fe" },
  { nombre: "Rosario", cp: "2000", provincia: "Santa Fe" },
  { nombre: "Rafaela", cp: "2300", provincia: "Santa Fe" },
  { nombre: "Venado Tuerto", cp: "2600", provincia: "Santa Fe" },
  { nombre: "Reconquista", cp: "3560", provincia: "Santa Fe" },
  { nombre: "Esperanza", cp: "3080", provincia: "Santa Fe" },
  { nombre: "Cañada de Gómez", cp: "2500", provincia: "Santa Fe" },
  { nombre: "Casilda", cp: "2170", provincia: "Santa Fe" },
  { nombre: "San Lorenzo", cp: "2200", provincia: "Santa Fe" },
  { nombre: "Capitán Bermúdez", cp: "2154", provincia: "Santa Fe" },
  { nombre: "Granadero Baigorria", cp: "2152", provincia: "Santa Fe" },
  { nombre: "Funes", cp: "2132", provincia: "Santa Fe" },
  { nombre: "Roldán", cp: "2134", provincia: "Santa Fe" },
  { nombre: "Pérez", cp: "2121", provincia: "Santa Fe" },
  { nombre: "Villa Gobernador Gálvez", cp: "2124", provincia: "Santa Fe" },
  { nombre: "Firmat", cp: "2630", provincia: "Santa Fe" },
  { nombre: "Sunchales", cp: "2322", provincia: "Santa Fe" },
  { nombre: "Vera", cp: "3550", provincia: "Santa Fe" },
  { nombre: "San Cristóbal", cp: "3070", provincia: "Santa Fe" },
  { nombre: "Tostado", cp: "3060", provincia: "Santa Fe" },
  { nombre: "Avellaneda", cp: "3561", provincia: "Santa Fe" },
  { nombre: "Las Rosas", cp: "2520", provincia: "Santa Fe" },
  { nombre: "Las Parejas", cp: "2505", provincia: "Santa Fe" },

  // ===== Mendoza =====
  { nombre: "Mendoza", cp: "5500", provincia: "Mendoza" },
  { nombre: "Godoy Cruz", cp: "5501", provincia: "Mendoza" },
  { nombre: "Guaymallén", cp: "5519", provincia: "Mendoza" },
  { nombre: "Las Heras", cp: "5539", provincia: "Mendoza" },
  { nombre: "Luján de Cuyo", cp: "5507", provincia: "Mendoza" },
  { nombre: "Maipú", cp: "5515", provincia: "Mendoza" },
  { nombre: "San Rafael", cp: "5600", provincia: "Mendoza" },
  { nombre: "General Alvear", cp: "5620", provincia: "Mendoza" },
  { nombre: "Malargüe", cp: "5613", provincia: "Mendoza" },
  { nombre: "Tunuyán", cp: "5560", provincia: "Mendoza" },
  { nombre: "San Martín", cp: "5570", provincia: "Mendoza" },
  { nombre: "Junín", cp: "5573", provincia: "Mendoza" },
  { nombre: "Rivadavia", cp: "5577", provincia: "Mendoza" },
  { nombre: "Tupungato", cp: "5561", provincia: "Mendoza" },
  { nombre: "La Consulta", cp: "5567", provincia: "Mendoza" },
  { nombre: "Uspallata", cp: "5545", provincia: "Mendoza" },

  // ===== Tucumán =====
  { nombre: "San Miguel de Tucumán", cp: "4000", provincia: "Tucumán" },
  { nombre: "Yerba Buena", cp: "4107", provincia: "Tucumán" },
  { nombre: "Tafí Viejo", cp: "4103", provincia: "Tucumán" },
  { nombre: "Concepción", cp: "4146", provincia: "Tucumán" },
  { nombre: "Aguilares", cp: "4152", provincia: "Tucumán" },
  { nombre: "Banda del Río Salí", cp: "4109", provincia: "Tucumán" },
  { nombre: "Lules", cp: "4129", provincia: "Tucumán" },
  { nombre: "Famaillá", cp: "4132", provincia: "Tucumán" },
  { nombre: "Monteros", cp: "4142", provincia: "Tucumán" },
  { nombre: "Tafí del Valle", cp: "4137", provincia: "Tucumán" },

  // ===== Salta =====
  { nombre: "Salta", cp: "4400", provincia: "Salta" },
  { nombre: "San Lorenzo", cp: "4401", provincia: "Salta" },
  { nombre: "Cafayate", cp: "4427", provincia: "Salta" },
  { nombre: "Orán", cp: "4530", provincia: "Salta" },
  { nombre: "San Ramón de la Nueva Orán", cp: "4530", provincia: "Salta" },
  { nombre: "Tartagal", cp: "4560", provincia: "Salta" },
  { nombre: "General Güemes", cp: "4430", provincia: "Salta" },
  { nombre: "Metán", cp: "4440", provincia: "Salta" },
  { nombre: "Rosario de la Frontera", cp: "4190", provincia: "Salta" },
  { nombre: "Cachi", cp: "4417", provincia: "Salta" },

  // ===== Jujuy =====
  { nombre: "San Salvador de Jujuy", cp: "4600", provincia: "Jujuy" },
  { nombre: "Palpalá", cp: "4612", provincia: "Jujuy" },
  { nombre: "Perico", cp: "4608", provincia: "Jujuy" },
  { nombre: "El Carmen", cp: "4607", provincia: "Jujuy" },
  { nombre: "Tilcara", cp: "4624", provincia: "Jujuy" },
  { nombre: "Humahuaca", cp: "4630", provincia: "Jujuy" },
  { nombre: "Purmamarca", cp: "4618", provincia: "Jujuy" },
  { nombre: "La Quiaca", cp: "4640", provincia: "Jujuy" },
  { nombre: "Libertador General San Martín", cp: "4512", provincia: "Jujuy" },

  // ===== Otras capitales =====
  { nombre: "San Fernando del Valle de Catamarca", cp: "4700", provincia: "Catamarca" },
  { nombre: "Catamarca", cp: "4700", provincia: "Catamarca" },
  { nombre: "La Rioja", cp: "5300", provincia: "La Rioja" },
  { nombre: "Santiago del Estero", cp: "4200", provincia: "Santiago del Estero" },
  { nombre: "La Banda", cp: "4300", provincia: "Santiago del Estero" },
  { nombre: "Resistencia", cp: "3500", provincia: "Chaco" },
  { nombre: "Corrientes", cp: "3400", provincia: "Corrientes" },
  { nombre: "Goya", cp: "3450", provincia: "Corrientes" },
  { nombre: "Mercedes", cp: "3470", provincia: "Corrientes" },
  { nombre: "Paso de los Libres", cp: "3230", provincia: "Corrientes" },
  { nombre: "Curuzú Cuatiá", cp: "3460", provincia: "Corrientes" },
  { nombre: "Esquina", cp: "3196", provincia: "Corrientes" },
  { nombre: "Bella Vista", cp: "3432", provincia: "Corrientes" },
  { nombre: "Posadas", cp: "3300", provincia: "Misiones" },
  { nombre: "Puerto Iguazú", cp: "3370", provincia: "Misiones" },
  { nombre: "Oberá", cp: "3360", provincia: "Misiones" },
  { nombre: "Eldorado", cp: "3380", provincia: "Misiones" },
  { nombre: "San Vicente", cp: "3364", provincia: "Misiones" },
  { nombre: "Apóstoles", cp: "3350", provincia: "Misiones" },
  { nombre: "Formosa", cp: "3600", provincia: "Formosa" },
  { nombre: "Clorinda", cp: "3610", provincia: "Formosa" },
  { nombre: "Paraná", cp: "3100", provincia: "Entre Ríos" },
  { nombre: "Concordia", cp: "3200", provincia: "Entre Ríos" },
  { nombre: "Gualeguaychú", cp: "2820", provincia: "Entre Ríos" },
  { nombre: "Concepción del Uruguay", cp: "3260", provincia: "Entre Ríos" },
  { nombre: "Colón", cp: "3280", provincia: "Entre Ríos" },
  { nombre: "Villaguay", cp: "3240", provincia: "Entre Ríos" },
  { nombre: "Diamante", cp: "3105", provincia: "Entre Ríos" },
  { nombre: "Victoria", cp: "3153", provincia: "Entre Ríos" },
  { nombre: "Gualeguay", cp: "2840", provincia: "Entre Ríos" },
  { nombre: "Federación", cp: "3206", provincia: "Entre Ríos" },
  { nombre: "Chajarí", cp: "3228", provincia: "Entre Ríos" },
  { nombre: "Crespo", cp: "3116", provincia: "Entre Ríos" },
  { nombre: "Nogoyá", cp: "3150", provincia: "Entre Ríos" },
  { nombre: "San Luis", cp: "5700", provincia: "San Luis" },
  { nombre: "Villa Mercedes", cp: "5730", provincia: "San Luis" },
  { nombre: "Merlo", cp: "5881", provincia: "San Luis" },
  { nombre: "San Juan", cp: "5400", provincia: "San Juan" },
  { nombre: "Caucete", cp: "5407", provincia: "San Juan" },
  { nombre: "Pocito", cp: "5429", provincia: "San Juan" },
  { nombre: "Rivadavia", cp: "5400", provincia: "San Juan" },
  { nombre: "Chimbas", cp: "5413", provincia: "San Juan" },
  { nombre: "Rawson", cp: "5429", provincia: "San Juan" },

  // ===== Patagonia =====
  { nombre: "Neuquén", cp: "8300", provincia: "Neuquén" },
  { nombre: "Plottier", cp: "8316", provincia: "Neuquén" },
  { nombre: "Cipolletti", cp: "8324", provincia: "Río Negro" },
  { nombre: "General Roca", cp: "8332", provincia: "Río Negro" },
  { nombre: "Viedma", cp: "8500", provincia: "Río Negro" },
  { nombre: "San Carlos de Bariloche", cp: "8400", provincia: "Río Negro" },
  { nombre: "Bariloche", cp: "8400", provincia: "Río Negro" },
  { nombre: "El Bolsón", cp: "8430", provincia: "Río Negro" },
  { nombre: "Cinco Saltos", cp: "8303", provincia: "Río Negro" },
  { nombre: "Villa Regina", cp: "8336", provincia: "Río Negro" },
  { nombre: "Allen", cp: "8328", provincia: "Río Negro" },
  { nombre: "Choele Choel", cp: "8360", provincia: "Río Negro" },
  { nombre: "San Antonio Oeste", cp: "8520", provincia: "Río Negro" },
  { nombre: "Las Grutas", cp: "8521", provincia: "Río Negro" },
  { nombre: "Sierra Grande", cp: "8532", provincia: "Río Negro" },
  { nombre: "San Martín de los Andes", cp: "8370", provincia: "Neuquén" },
  { nombre: "Villa La Angostura", cp: "8407", provincia: "Neuquén" },
  { nombre: "Junín de los Andes", cp: "8371", provincia: "Neuquén" },
  { nombre: "Zapala", cp: "8340", provincia: "Neuquén" },
  { nombre: "Cutral Có", cp: "8322", provincia: "Neuquén" },
  { nombre: "Plaza Huincul", cp: "8318", provincia: "Neuquén" },
  { nombre: "Centenario", cp: "8309", provincia: "Neuquén" },
  { nombre: "Senillosa", cp: "8316", provincia: "Neuquén" },
  { nombre: "Chos Malal", cp: "8353", provincia: "Neuquén" },
  { nombre: "Rawson", cp: "9103", provincia: "Chubut" },
  { nombre: "Trelew", cp: "9100", provincia: "Chubut" },
  { nombre: "Puerto Madryn", cp: "9120", provincia: "Chubut" },
  { nombre: "Comodoro Rivadavia", cp: "9000", provincia: "Chubut" },
  { nombre: "Esquel", cp: "9200", provincia: "Chubut" },
  { nombre: "Gaiman", cp: "9105", provincia: "Chubut" },
  { nombre: "Dolavon", cp: "9107", provincia: "Chubut" },
  { nombre: "Río Gallegos", cp: "9400", provincia: "Santa Cruz" },
  { nombre: "Caleta Olivia", cp: "9011", provincia: "Santa Cruz" },
  { nombre: "Pico Truncado", cp: "9015", provincia: "Santa Cruz" },
  { nombre: "El Calafate", cp: "9405", provincia: "Santa Cruz" },
  { nombre: "El Chaltén", cp: "9301", provincia: "Santa Cruz" },
  { nombre: "Puerto Deseado", cp: "9050", provincia: "Santa Cruz" },
  { nombre: "Ushuaia", cp: "9410", provincia: "Tierra del Fuego" },
  { nombre: "Río Grande", cp: "9420", provincia: "Tierra del Fuego" },
  { nombre: "Tolhuin", cp: "9412", provincia: "Tierra del Fuego" },

  // ===== Chaco extra =====
  { nombre: "Presidencia Roque Sáenz Peña", cp: "3700", provincia: "Chaco" },
  { nombre: "Sáenz Peña", cp: "3700", provincia: "Chaco" },
  { nombre: "Villa Ángela", cp: "3540", provincia: "Chaco" },
  { nombre: "Charata", cp: "3730", provincia: "Chaco" },
  { nombre: "Las Breñas", cp: "3722", provincia: "Chaco" },
  { nombre: "Quitilipi", cp: "3530", provincia: "Chaco" },
  { nombre: "Castelli", cp: "3705", provincia: "Chaco" },
  { nombre: "General San Martín", cp: "3540", provincia: "Chaco" },
]

// ----- Búsqueda fuzzy: prioriza coincidencias al inicio del nombre -----
export function buscarLocalidad(query: string, max = 8): LocalidadAR[] {
  const q = norm(query)
  if (q.length < 2) return []

  const scored: { loc: LocalidadAR; score: number }[] = []
  for (const loc of LOCALIDADES_AR) {
    const n = norm(loc.nombre)
    let score = -1
    if (n === q) score = 100               // match exacto
    else if (n.startsWith(q)) score = 90   // empieza con el query
    else if (n.includes(" " + q)) score = 80 // palabra entera dentro
    else if (n.includes(q)) score = 60     // substring
    if (score >= 0) scored.push({ loc, score })
  }
  scored.sort((a, b) => b.score - a.score || a.loc.nombre.localeCompare(b.loc.nombre))
  return scored.slice(0, max).map(s => s.loc)
}
